// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      const { data, error } = await supabase.auth.getSession();
      if (error) {
        console.warn("[Auth Attacher] Session fetch error:", error.message);
      }
      let token = data.session?.access_token;

      // If token exists but expires in < 30 seconds, attempt explicit refresh
      if (data.session?.expires_at) {
        const expiresAtMs = data.session.expires_at * 1000;
        if (Date.now() > expiresAtMs - 30_000) {
          const { data: refreshed } = await supabase.auth.refreshSession();
          if (refreshed?.session?.access_token) {
            token = refreshed.session.access_token;
          }
        }
      }

      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    } catch (err) {
      console.error("[Auth Attacher] Middleware failed:", err);
      return next({ headers: {} });
    }
  },
)
